language: python
python:
- '2.7'

before_install:
    - pip install coveralls
    - pip install -r dev_requirements.txt
    - pip install -r test_requirements.txt

install:
    - python setup.py install

script:
    - nosetests --with-coverage --cover-package=package/cloudshell/networking/cisco --where=package/tests
    - python setup.py sdist --format zip

after_success:
    - coveralls
